"""Initial migration

Revision ID: 1bfc88d6d313
Revises: 
Create Date: 2024-06-18 18:42:24.159674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfc88d6d313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('category', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('category', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
