name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Lint with autopep8
        run: |
          source venv/bin/activate
          autopep8 --in-place --aggressive --aggressive --recursive backend/
          # Check if there are any changes made by autopep8
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Style: autopep8 formatting"
            git push
          fi

      - name: Run unittests
        run: |
          source venv/bin/activate
          python -m unittest backend.test_flaskr

      - name: Clear GitHub Actions cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache
          restore-keys: |
            ${{ runner.os }}-cache
